# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.
name = "formz"
version = "1.0.0"
description = "Accessible, type safe form parsing and generating for Gleam"
licences = ["Unlicense"]
repository = { type = "github", user = "bentomas", repo = "formz" }
gleam = ">= 1.6.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
justin = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
